FROM golang:1.17-alpine AS build

RUN apk add --update git

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 go build -o /app/products-api
FROM scratch
WORKDIR /
COPY --from=build /app/products-api /app/products-api
# RUN chmod +x ./app/products-api/main
CMD ["/app/products-api"]